
services:
  #db:
    #build: ./
    #restart: always
    #ports:
    #  - 1433:1433
    #environment:
    #  - SQLITE_PATH=/sqlite.db
    #env_file:
    #  - .env
    #volumes:
    #  - "./static:/app/app/static/"
    #  - "./data/sqlite.db:/sqlite.db"

  app:
    build: ./
    #restart: always
    ports:
      - 8000:8000
    command: sh -c "uvicorn app.main:app --port=8000 --host 0.0.0.0"
    volumes:
      - .:/app
